### ISSUE TITLE
mobileOGs-pl-kyanite.py not working

### ISSUE THREAD

**Issue by sciguy** [clb21565/mobileOG-db#11]
Since the update yesterday, mobileOGs-pl-kyanite.py no longer works. Line 25 is split on 2 lines.

When I manually fix the split line the program runs but no longer returns the Alignment output file: *.mobileOG.Alignment.Out.csv

**Comment by clb21565** [comment]
OOF-- thanks a million for bearing with me. I have updated the issue and tested it out on a couple of samples. let me know if anything else comes up.
