### ISSUE TITLE
Error: Protein sequences expected

### ISSUE THREAD

**Issue by asierFernandezP** [clb21565/mobileOG-db#12]
Hi,

I have tried to run the tool again today but I get a new error that I was not getting before:

"Error: The sequences are expected to be proteins but only contain DNA letters"

How should I know specify that the input fasta is DNA? I use the following parameters as it is described in the manual: -k 15 -e 1e-20 -p 90 -q 90.

Thank you,
Asier

**Comment by clb21565** [comment]
hi there! I am not sure what's going on there-- nothing in the shell script should have changed. Can you provide the full command you used?

**Comment by asierFernandezP** [comment]
Apparently it was my own error when running DIAMOND. It is solved and it works fine! Thanks again, and I will let you any if I have any further comments!

Asier

**Comment by clb21565** [comment]
great! closing for now-- please do let me know if anything else comes up.
