### ISSUE TITLE
Error: target with no hsps

### ISSUE THREAD

**Issue by asierFernandezP** [clb21565/mobileOG-db#13]
Hi Connor,

I ran the scripts in 2 different databases, and while it worked perfectly in one of them, in the other I got the following error:

```
Computing alignments... Error: generate_output: target with no hsps.
Empty diamond output. No hits returned from diamond search.
```

In that case (it is a phage-plasmid database) no output files were generated. Maybe should I try changing some parameters (currently I use -k 15 -e 1e-20 -p 90 -q 90 -  although I would like to know which other flags are supported (like --id, etc.)

**Comment by clb21565** [comment]
Hey there! -p corresponds to --id setting in blastp and -q is query cover. Apologies for the confusion-- we'll be making the commands more intuitive in a future release. 

RE no hits-- if you modify the -p / -q setting, you should probably see some hits. An especially low value might be warranted to detected very diverged phage sequences.

**Comment by asierFernandezP** [comment]
Thanks for the clarification! However, I have tried to run it lowering the thresholds (-k 10 -e 1e-10 -p 10 -q 10) and still no output is reported.
