### ISSUE TITLE
Script names

### ISSUE THREAD

**Issue by loulanomics** [clb21565/mobileOG-db#2]
Hello!

I think I got your pipeline to work with a few modifications. Just checking if I did this correctly and am getting the expected output.

### 1. python version

In [UsageGuidance.md](https://github.com/clb21565/mobileOG-db/blob/main/mobileOG-pl/UsageGuidance.md), it says dependencies are python 3.7 with pandas, argparse, and itertools.

So I specified python 3.7 - `conda create -n mobileOG-db python=3.7`

However, I got this error:

```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment -

Specifications:

  - argparse -> python[version='2.6.*|2.7.*|3.4.*|3.5.*|3.6.*']

Your python: python=3.7
```

Which was fixed by specifying 3.6.15 `conda create -n mobileOG-db python=3.6.15`

### 2. unicode decode error

With help from [this](https://www.kaggle.com/code/paultimothymooney/how-to-resolve-a-unicodedecodeerror-for-a-csv-file/notebook), I was able to solve these -
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xee in position 2: invalid continuation byte
```

In <b>mobileOGs-pl-kyanite.py</b>, change line 19 to -
```
df_OUT=pd.read_csv(args.i,sep="\t",encoding='ascii')
```
and line 61 to (I could not get it to work with `args.m`)-
```
Metadata=pd.read_csv('mobileOG-db-beatrix-1.5.All.csv',encoding='utf-8')
```

### 3. script names
I think [UsageGuidance.md](https://github.com/clb21565/mobileOG-db/blob/main/mobileOG-pl/UsageGuidance.md) is not up to date? Is "mobileOG-pl.sh" the same as "[mobileOGs-pl-kyanite.sh](https://github.com/clb21565/mobileOG-db/blob/main/mobileOG-pl/mobileOGs-pl-kyanite.sh)?"

Within the shell script, `mobileOGs-pl.py` is then changed to `mobileOGs-pl-kyanite.py`?

### 4. executables
The markdown says

```
mobileOG-pl.sh -i -d mobileOG-db_beatrix-1.X.dmnd -k 15 -e 1e-20 -p 90 -q 90
```
So I put my fasta file after `-i`, and made the script executable (`chmod u+x mobileOGs-pl-kyanite.sh`). Also, everything prints to the terminal, so I also redirected. 

The final command looks like this -

```
./mobileOGs-pl-kyanite.sh -i test.fasta -d mobileOG-db-beatrix-1.5.All.dmnd -k 15 -e 1e-20 -p 90 -q 90 > test.txt
```

### 5. verbose
After redirecting, output to terminal is like this... is there a way of turning it off? (there are many thousands of sequences haha)
```
...
Finding genes in sequence #32268 (1023 bp)...done!
Finding genes in sequence #32269 (2088 bp)...done!
Finding genes in sequence #32270 (4827 bp)...done!
Finding genes in sequence #32271 (1319 bp)...done!
Finding genes in sequence #32272 (5211 bp)...done!
Finding genes in sequence #32273 (1350 bp)...done!
...
```

### 6. output
Finally, the output test.fasta.summary.csv looks like this -

```
$ head -3 test.fasta.summary.csv

,key_0,Specific Contig_x,Bacteriophages,Insertion sequences,Integrative elements,Multiple,Plasmids,Total Number of Hits,Percent Bacteriophages,Percent Insertion sequences,Percent Integrative elements,Percent Plasmids,Percent Multiple,Specific Contig_y,Amount of Unique ORFs
0,S10B_S4_000000000087,S10B_S4_000000000087,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,100.0,0.0,0.0,S10B_S4_000000000087,1
1,S10B_S4_000000000117,S10B_S4_000000000117,1.0,0.0,0.0,0.0,0.0,1.0,100.0,0.0,0.0,0.0,0.0,S10B_S4_000000000117,1
```

Is this expected?

Thank you!!

**Comment by clb21565** [comment]
Thanks for the detailed question and for point out these issues! 

1. I'll change the installation instructions to specify 3.6.15 -- not sure why this is happening, but this also might be fixable if one specifies the python version in the shell script (python3.6 mobileOGs-pl.py) 
2. I'll look into why the args.m doesn't work to correct it and push this in a new release soon. 
3. Yes, this is correct. 
4. This looks good. 
5. This can be changed by adding -q to the mobileOGs shell script - I will make this the default in the next release.
6. This is the correct output, but it is messier than its intended to be. Will be removing redundant columns. 

Thanks for trying out the pipeline and for reaching out - let me know if I can be of any further assistance.

**Comment by loulanomics** [comment]
Thank you for the quick response and handy tool!
