### ISSUE TITLE
Product descriptions for functional annotations

### ISSUE THREAD

**Issue by oschwengers** [clb21565/mobileOG-db#3]
First of all, thanks a lot for and congratulations to this great resource of MGE proteins! This is an important effort towards a systematic order of MGE related proteins and functions.

Also, this might be a wonderful resource for functional annotation pipelines like for instance [Bakta](https://github.com/oschwengers/bakta). However, I could find only gene symbols but no related product descriptions which are required for such purposes. Have I merely overlooked them somewhere or are these actually lacking? And if they are lacking, would it be possible to provide them?

Again, thanks a lot!

**Comment by clb21565** [comment]
Thanks so much for the interest in the resource and the kind words! I am happy to accommodate however I can. 

Are you looking for descriptions of the protein function? That data does exist-- in the mobileOG metadata, it would be the manual annotation. Alternatively, I can incorporate protein function labels using the eggnog/pfam data. Let me know what you think.

**Comment by oschwengers** [comment]
Thanks for the quick reply! Maybe I wasn't specific enought, with "descriptions" I mean the gene product names or some call them descriptions or definitions.

For example `mobileOG_000377395` which belongs to cluster `mobileOG_000376753` and is linked to the RefSeq sequence `WP_027813522.1` has a decent gene symbol `trfA` but for the `Manual annotation` the following *very* long and comprehensive description is given: `Required for initiation of plasmid DNA replication, along with host-derived DnaA and other host proteins. Both forms of the protein are capable of initiating plasmid replication in a number of Gram-negative. Binds to 8 17-base pair repeat sequences (iterons) in the RK2 minimal replication origin (oriV), opening the origin of replication. oriV opening does not absolutely require the presence of nucleotides; formation of open complex is somewhat enhanced by ATP or ATP gamma S, while DnaA or HU is required for full opening.`

This is great resource with lots of information. However, for the task of functional annotation we need the gene symbol `trfA` and a proper gene product name/description/definition. For example, for [WP_027813522.1](https://www.ncbi.nlm.nih.gov/protein/WP_027813522.1) RefSeq provides: `plasmid replication initiator TrfA`.

If it would be possible for you to provide these gene product names, we could use this resource to streamline the annotation of  MGE genes/proteins.

**Comment by clb21565** [comment]
Ah, I see! OK- that’s pretty doable. It’s on the to-do list and I’ll put it on the website with the next release and send another message your way.

**Comment by oschwengers** [comment]
That would be awesome. I'm really looking forward to it. Thanks a lot!

**Comment by clb21565** [comment]
OK -- a couple of follow up questions -- 

would you want the entire database (all ~770k proteins) or would the the protein family representatives (the entire db clustered at 40% identity/50% qc) suffice?

**Comment by clb21565** [comment]
Working on this -- I think we can provide whatever clusters you like best-- provided we are able to do it in a relatively simple and reproducible way. I'll share those results when I get them. 

As a note though, I expect there will be a trade-off on coverage vs. interpretability-- many of these proteins might only have PFAM domains -- which complicates naming, description, etc. All sequences from mobileOG-db are directly derived from MGE sequences, so its unlikely they are errant homologs. 

To combat this-- we could do "XX-domain containing protein" or something like that, as is done by UniProt. Let me know what you think. 
Thanks again!
Connor

**Comment by clb21565** [comment]
Hi there, 
I think I have the product descriptions you're looking for (and protein clusters at 90% identity). One last question though -- what is the max character length you're expecting for the product descriptions? Is <=50 OK? (the example you provided was 35).

**Comment by oschwengers** [comment]
Great!
I think there is no strict limit but `<= 50` on average sounds reasonable.
