### ISSUE TITLE
zsh: permission denied: 

### ISSUE THREAD

**Issue by Oelsakha** [clb21565/mobileOG-db#5]
Hi 
I am trying to run final step ./mobileOG-db-main/mobileOG-pl/mobileOGs-pl-kyanite.sh -i S5.fasta -d mobileOG-db-beatrix-1.X.dmnd -m mobileOG-db-beatrix-1.6-All.csv -k 15 -e 1e-20 -p 90 -q 90
but I got this error zsh: permission denied: ./mobileOG-db-main/mobileOG-pl/mobileOGs-pl-kyanite.sh 

can you help me please?

thank you

**Comment by clb21565** [comment]
added this to the documentation

**Comment by Oelsakha** [comment]
I have another error after running 

    raise KeyError(key)
KeyError: 'value'

and in the file I got , 
these columns are empty 

Major mobileOG Category,Minor mobileOG Category, Best Hit Accession ID.

**Comment by clb21565** [comment]
this usually means there was no hit against our database. we're working on fixing the error message

**Comment by clb21565** [comment]
you can confirm it is this by lowering the id and qc parameters

**Comment by Oelsakha** [comment]
great, thank you so much !

Excuse me, can you explain how to do that?
