### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Ales-ibt** [clb21565/mobileOG-db#7]
Hello! Thank you for putting together this database, it is exactly what I need to try to improve the annotation of proteins on predicted MGEs. However, can you set up a license in the repo? Just to be on the safe side. 

Thanks in advance!

Alejandra.

**Comment by clb21565** [comment]
Thanks for your interest in the database! I have just added the license to the repo. Thank you for the comment and please let me know if you need anything else.
